canadian_hl_score: 0
cannonical_set: BBD
cannonical_type: Creature
companions:
- Gyruda, Doom of Depths
- Jegantha, the Wellspring
- Keruga, the Macrosage
- Lutri, the Spellchaser
- Umori, the Collector
- Yorion, Sky Nomad
effective_cost:
- B
flat_cost: 4
formats:
- 1v1 Commander
- Arena
- Block Constructed
- Canadian Highlander
- Commander / EDH
- 'Commander: Rule 0'
- Duel Commander
- Gladiator
- Highlander
- Historic
- Legacy
- Leviathan
- Limited
- Modern
- Oathbreaker
- Pauper
- Pauper Duel Commander
- Pauper EDH
- Pioneer
- Vintage
has_activated_abilities: false
is_mtgo: true
is_permanent: true
mana_cost: 3B
mana_cost_converted: 4
name: Prakhata Club Security
power_toughness: 3/4
printings:
- MYS1:
    alterations:
    - Normal
    border_color: B
    cannonical: false
    frame: m15
    name: Mystery Booster
    rarity: common
    release_date: 2020-03-14
- BBD:
    alterations:
    - Foil
    - Normal
    border_color: B
    frame: m15
    mtgo_foil_id: 69039
    mtgo_id: 69038
    name: Battlebond
    number: 155
    rarity: common
    release_date: 2018-06-08
    wizards_id: 446123
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=446123
- KLD:
    alterations:
    - Foil
    - Normal
    border_color: B
    frame: m15
    mtgo_foil_id: 61684
    mtgo_id: 61683
    name: Kaladesh
    number: 98
    rarity: common
    release_date: 2016-09-30
    wizards_id: 417671
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=417671
slug: prakhata-club-security
subtype: Viashino Skeleton
subtype_tokens:
- Viashino
- Skeleton
tags: card-color-black card-color-black-cost-4 card-type-creature
tapped_id: 18452
type: Creature
url: http://tappedout.net/mtg-card/prakhata-club-security/
