canadian_hl_score: 0
cannonical_set: PLS
cannonical_type: Instant
companions:
- Gyruda, Doom of Depths
- Jegantha, the Wellspring
- Kaheera, the Orphanguard
- Keruga, the Macrosage
- Lurrus of the Dream-Den
- Lutri, the Spellchaser
- Umori, the Collector
- Yorion, Sky Nomad
- Zirda, the Dawnwaker
effective_cost:
- W
flat_cost: 4
formats:
- 1v1 Commander
- Canadian Highlander
- Commander / EDH
- 'Commander: Rule 0'
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Oathbreaker
- Pauper Duel Commander
- Premodern
- Vintage
has_activated_abilities: false
is_mtgo: true
is_permanent: false
mana_cost: 3W
mana_cost_converted: 4
name: Surprise Deployment
printings:
- PLS:
    alterations:
    - Foil
    - Normal
    border_color: B
    frame: original
    mtgo_foil_id: 15232
    mtgo_id: 15231
    name: Planeshift
    number: 18
    rarity: uncommon
    release_date: 2001-02-01
    wizards_id: 26403
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=26403
rules: "Play Surprise Deployment only during combat.\r\n\r\nYou may put a nonwhite\
  \ creature card from your hand into play. At end of turn, return that creature to\
  \ your hand. (Return it only if it's in play.)"
slug: surprise-deployment
tags: card-color-white card-color-white-cost-4 card-type-instant
tapped_id: 5003
type: Instant
url: http://tappedout.net/mtg-card/surprise-deployment/
