activated_abilities:
- '(1): Return target land you control to its owner''s hand.'
- '(1), Discard a land card: Draw a card.'
canadian_hl_score: 0
cannonical_set: 9ED
cannonical_type: Enchantment
companions:
- Gyruda, Doom of Depths
- Jegantha, the Wellspring
- Kaheera, the Orphanguard
- Lurrus of the Dream-Den
- Lutri, the Spellchaser
- Umori, the Collector
- Yorion, Sky Nomad
- Zirda, the Dawnwaker
effective_cost:
- U
flat_cost: 2
formats:
- 1v1 Commander
- Block Constructed
- Canadian Highlander
- Commander / EDH
- 'Commander: Rule 0'
- Duel Commander
- Highlander
- Legacy
- Leviathan
- Limited
- Modern
- Oathbreaker
- Pauper Duel Commander
- Premodern
- Tiny Leaders
- Vintage
has_activated_abilities: true
is_mtgo: true
is_permanent: true
mana_cost: 1U
mana_cost_converted: 2
name: Trade Routes
printings:
- 9ED:
    alterations:
    - Foil
    - Normal
    border_color: W
    frame: modern
    mtgo_foil_id: 22476
    mtgo_id: 22475
    name: Ninth Edition
    number: 108
    rarity: rare
    release_date: 2005-07-29
    wizards_id: 83302
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=83302
- 9EDFBB:
    alterations:
    - Normal
    border_color: B
    cannonical: false
    frame: modern
    mtgo_foil_id: 22476
    mtgo_id: 22475
    name: Ninth Edition Foreign Black Border
    rarity: rare
    release_date: 2005-07-29
- 8ED:
    alterations:
    - Foil
    - Normal
    border_color: W
    frame: modern
    mtgo_foil_id: 19170
    mtgo_id: 19169
    name: Eighth Edition
    rarity: rare
    release_date: 2003-07-28
    wizards_id: 45272
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=45272
- MMQ:
    alterations:
    - Foil
    - Normal
    - The List
    border_color: B
    frame: original
    mtgo_foil_id: 13422
    mtgo_id: 13421
    name: Mercadian Masques
    rarity: rare
    release_date: 1999-10-04
    wizards_id: 19675
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=19675
rules: "(1): Return target land you control to its owner's hand.\r\n\r\n(1), Discard\
  \ a land card: Draw a card."
slug: trade-routes
tags: card-color-blue card-color-blue-cost-2 card-type-enchantment
tapped_id: 5915
type: Enchantment
url: http://tappedout.net/mtg-card/trade-routes/
