canadian_hl_score: 0
cannonical_set: VOW
cannonical_type: Creature
companions:
- Keruga, the Macrosage
- Lutri, the Spellchaser
- Obosh, the Preypiercer
- Umori, the Collector
- Yorion, Sky Nomad
effective_cost:
- B
flat_cost: 5
formats:
- 1v1 Commander
- Alchemy
- Arena
- Block Constructed
- Brawl
- Canadian Highlander
- Commander / EDH
- 'Commander: Rule 0'
- Duel Commander
- Gladiator
- Highlander
- Historic
- Legacy
- Leviathan
- Limited
- Modern
- Oathbreaker
- Pauper Duel Commander
- Pioneer
- Pre-release
- Standard
- Vintage
has_activated_abilities: false
is_mtgo: true
is_permanent: true
keywords:
- Sacrifice
- Counters
mana_cost: 3BB
mana_cost_converted: 5
name: Wedding Security
power_toughness: 4/4
printings:
- DBL:
    alterations:
    - Foil
    - Normal
    border_color: B
    cannonical: false
    frame: m15
    name: 'Innistrad: Double Feature'
    number: 405
    rarity: uncommon
    release_date: 2022-01-21
- VOW:
    alterations:
    - Foil
    - Normal
    border_color: B
    frame: m15
    name: 'Innistrad: Crimson Vow'
    number: 138
    rarity: uncommon
    release_date: 2021-11-11
    variations:
    - alterations:
      - Foil
      - Normal
      identifier: '299'
    wizards_id: 540991
    wizards_url: http://gatherer.wizards.com/Pages/Card/Details.aspx?&multiverseid=540991
rules: Whenever this attacks, you may sacrifice a Blood token. If you do, put a +1/+1
  counter on this and draw a card.
slug: wedding-security
subtype: Vampire Soldier
subtype_tokens:
- Vampire
- Soldier
tags: card-color-black card-color-black-cost-5 card-type-creature
tapped_id: 25508
type: Creature
url: http://tappedout.net/mtg-card/wedding-security/
